"""empty message

Revision ID: 30782b9a311f
Revises: 98a54ce9764a
Create Date: 2020-11-17 18:09:47.635535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30782b9a311f'
down_revision = '98a54ce9764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'date')
    # ### end Alembic commands ###
