"""empty message

Revision ID: 4a12ba6b4ee6
Revises: b089f7689caf
Create Date: 2020-11-23 17:47:17.259304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a12ba6b4ee6'
down_revision = 'b089f7689caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('date', sa.String(length=255), nullable=False))
    op.add_column('operations', sa.Column('service', sa.String(length=255), nullable=False))
    op.add_column('operations', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('operations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'operations', 'services', ['service_id'], ['id'])
    op.create_foreign_key(None, 'operations', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'user_id')
    op.drop_column('operations', 'service_id')
    op.drop_column('operations', 'service')
    op.drop_column('operations', 'date')
    # ### end Alembic commands ###
