"""empty message

Revision ID: 57459ff3d771
Revises: 4a12ba6b4ee6
Create Date: 2020-11-23 17:49:59.388358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57459ff3d771'
down_revision = '4a12ba6b4ee6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Commerce_review', sa.Column('id_review', sa.Integer(), nullable=False))
    op.drop_constraint('Commerce_review_ibfk_1', 'Commerce_review', type_='foreignkey')
    op.create_foreign_key(None, 'Commerce_review', 'review', ['id_review'], ['id'])
    op.drop_column('Commerce_review', 'id')
    op.add_column('user_review', sa.Column('id_review', sa.Integer(), nullable=False))
    op.drop_constraint('user_review_ibfk_1', 'user_review', type_='foreignkey')
    op.create_foreign_key(None, 'user_review', 'review', ['id_review'], ['id'])
    op.drop_column('user_review', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_review', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_review', type_='foreignkey')
    op.create_foreign_key('user_review_ibfk_1', 'user_review', 'review', ['id'], ['id'])
    op.drop_column('user_review', 'id_review')
    op.add_column('Commerce_review', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Commerce_review', type_='foreignkey')
    op.create_foreign_key('Commerce_review_ibfk_1', 'Commerce_review', 'review', ['id'], ['id'])
    op.drop_column('Commerce_review', 'id_review')
    # ### end Alembic commands ###
