"""empty message

Revision ID: 6224dca26eb9
Revises: eb24d4692a2f
Create Date: 2020-11-25 16:51:42.486514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6224dca26eb9'
down_revision = 'eb24d4692a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_type', sa.Column('service_type_id', sa.String(length=255), nullable=True))
    op.drop_column('service_type', 'service_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_type', sa.Column('service_type', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('service_type', 'service_type_id')
    # ### end Alembic commands ###
