"""empty message

Revision ID: 98a54ce9764a
Revises: 7418064eb9dd
Create Date: 2020-11-17 17:21:59.754848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a54ce9764a'
down_revision = '7418064eb9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('Paseador', 'Canguro', 'Adiestrador', 'Aseo'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Services',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('animal_type', sa.Enum('perro', 'gato', 'conejo', 'roedores', 'aves'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Enum('amigable', 'dominante', 'nervioso', 'agresivo', 'jugueton'), nullable=False),
    sa.Column('sex', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('diseases', sa.Text(), nullable=False),
    sa.Column('sterilized', sa.Boolean(create_constraint=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.Enum('Paseador', 'Canguro', 'Adiestrador', 'Aseo'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comerce_id', sa.Integer(), nullable=True),
    sa.Column('review', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['comerce_id'], ['commerce.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Review',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column('user', sa.Column('biografy', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=30), nullable=False))
    op.create_unique_constraint(None, 'user', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    op.drop_column('user', 'location')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'image')
    op.drop_column('user', 'biografy')
    op.drop_table('User_Review')
    op.drop_table('review')
    op.drop_table('commerce')
    op.drop_table('animals')
    op.drop_table('User_Services')
    op.drop_table('services')
    # ### end Alembic commands ###
