"""empty message

Revision ID: a3bb99b37ac5
Revises: 57459ff3d771
Create Date: 2020-11-24 11:21:37.597628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3bb99b37ac5'
down_revision = '57459ff3d771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_review')
    op.drop_table('Commerce_review')
    op.drop_table('commerce')
    op.add_column('operations', sa.Column('hired_time', sa.Integer(), nullable=False))
    op.add_column('operations', sa.Column('service_id_hired', sa.Integer(), nullable=False))
    op.add_column('operations', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('operations', sa.Column('user_id_who_hire', sa.Integer(), nullable=False))
    op.drop_constraint('operations_ibfk_1', 'operations', type_='foreignkey')
    op.drop_constraint('operations_ibfk_2', 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'services', ['service_id_hired'], ['id'])
    op.create_foreign_key(None, 'operations', 'user', ['user_id_who_hire'], ['id'])
    op.drop_column('operations', 'user_id')
    op.drop_column('operations', 'price')
    op.drop_column('operations', 'service')
    op.drop_column('operations', 'service_id')
    op.drop_column('review', 'review_type')
    op.add_column('services', sa.Column('id_service_type', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('id_user_offer', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('price_h', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'services', 'service_type', ['id_service_type'], ['id'])
    op.create_foreign_key(None, 'services', 'user', ['id_user_offer'], ['id'])
    op.drop_column('services', 'price')
    op.drop_column('services', 'service')
    op.drop_column('services', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', mysql.TEXT(), nullable=True))
    op.add_column('services', sa.Column('service', mysql.ENUM('Paseador', 'Canguro', 'Adiestrador', 'Aseo'), nullable=True))
    op.add_column('services', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'price_h')
    op.drop_column('services', 'id_user_offer')
    op.drop_column('services', 'id_service_type')
    op.add_column('review', sa.Column('review_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('operations', sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('operations', sa.Column('service', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('operations', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.add_column('operations', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key('operations_ibfk_2', 'operations', 'user', ['user_id'], ['id'])
    op.create_foreign_key('operations_ibfk_1', 'operations', 'services', ['service_id'], ['id'])
    op.drop_column('operations', 'user_id_who_hire')
    op.drop_column('operations', 'total_price')
    op.drop_column('operations', 'service_id_hired')
    op.drop_column('operations', 'hired_time')
    op.create_table('commerce',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image', mysql.TEXT(), nullable=True),
    sa.Column('schedule', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='commerce_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('Commerce_review',
    sa.Column('id_commerce_destination', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_review', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_commerce_destination'], ['commerce.id'], name='Commerce_review_ibfk_2'),
    sa.ForeignKeyConstraint(['id_review'], ['review.id'], name='Commerce_review_ibfk_3'),
    sa.PrimaryKeyConstraint('id_commerce_destination'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user_review',
    sa.Column('id_user_destination', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_review', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_review'], ['review.id'], name='user_review_ibfk_3'),
    sa.ForeignKeyConstraint(['id_user_destination'], ['user.id'], name='user_review_ibfk_2'),
    sa.PrimaryKeyConstraint('id_user_destination'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('service_type')
    # ### end Alembic commands ###
