"""empty message

Revision ID: b089f7689caf
Revises: d3c7ed89e206
Create Date: 2020-11-23 17:33:56.283027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b089f7689caf'
down_revision = 'd3c7ed89e206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commerce', 'service')
    op.drop_column('review', 'date')
    op.drop_column('services', 'schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('schedule', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('review', sa.Column('date', mysql.DATETIME(), nullable=False))
    op.add_column('commerce', sa.Column('service', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
