"""empty message

Revision ID: d3c7ed89e206
Revises: 3fdb794045f8
Create Date: 2020-11-23 17:15:48.729676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c7ed89e206'
down_revision = '3fdb794045f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('Paseador', 'Canguro', 'Adiestrador', 'Aseo'), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('animal_type', sa.Enum('perro', 'gato', 'conejo', 'roedores', 'aves'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('personality', sa.Enum('amigable', 'dominante', 'nervioso', 'agresivo', 'jugueton'), nullable=False),
    sa.Column('gender', sa.Boolean(create_constraint=False), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('diseases', sa.Text(), nullable=False),
    sa.Column('sterilized', sa.Boolean(create_constraint=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commerce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_author', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_user_author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Commerce_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_commerce_destination', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['id_commerce_destination'], ['commerce.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_commerce_destination')
    )
    op.create_table('user_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user_destination', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['id_user_destination'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_user_destination')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_review')
    op.drop_table('Commerce_review')
    op.drop_table('review')
    op.drop_table('commerce')
    op.drop_table('animals')
    op.drop_table('services')
    op.drop_table('operations')
    # ### end Alembic commands ###
