"""empty message

Revision ID: dc8296aedf1c
Revises: e2301aa5929e
Create Date: 2021-01-17 18:48:28.842533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc8296aedf1c'
down_revision = 'e2301aa5929e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'user', ['phone'], unique=True)
    # ### end Alembic commands ###
