"""empty message

Revision ID: eb24d4692a2f
Revises: a3bb99b37ac5
Create Date: 2020-11-25 16:41:00.198297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb24d4692a2f'
down_revision = 'a3bb99b37ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user', 'location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
